radio=int(input("ingrese el valor del radio "))
pi=int(3.1416) 
per=str(2*pi*radio) 
are=str(pi*radio*radio) 
vol=str(4*pi*(radio*radio*radio)/3) 
print("el perimetro equivale a "+ per +", el area equivale a "+ are +" y el volumen es igual a "+ vol)